In [4]:
lis = [1,2,3]

In [8]:
lis

[1, 2, 3]

In [10]:
import numpy as np

In [12]:
arr = np.array([1,2,3])

In [14]:
arr

array([1, 2, 3])

In [16]:
arr = np.array(lis)

In [18]:
arr

array([1, 2, 3])

In [20]:
matr = [[1,2,3],
        [4,5,6],
        [7,8,9]]


In [22]:
np.array(matr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(0, 10, dtype = float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [30]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [33]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [35]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.linspace(0,10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [41]:
np.ones((3,3,3)).shape

(3, 3, 3)

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
np.random.rand(5,5)

array([[0.65262548, 0.69213566, 0.58521682, 0.75963595, 0.84496338],
       [0.42365421, 0.51286376, 0.98691325, 0.79091627, 0.27855612],
       [0.72644602, 0.53333232, 0.74671208, 0.07640164, 0.19235886],
       [0.04272555, 0.32410382, 0.24387227, 0.53119145, 0.97546955],
       [0.82986767, 0.43681456, 0.83227809, 0.2515037 , 0.88019063]])

In [50]:
np.random.randn(2)

array([0.61729976, 1.01111488])

In [53]:
np.random.randint(-10, 10, (2,2))

array([[-8,  5],
       [-3, -3]])

In [55]:
np.random.randint(-10, 10, 10)

array([-5, -3, -1,  1,  5, -3,  3,  1, -2, -7])

In [58]:
arr = np.arange(16)

In [59]:
arr_rand = np.random.randint(-20, 21, 16)

In [60]:
arr_rand

array([-19,  13,   0, -14, -16,   5,  14,   1, -17, -14,  -9,  -4,  -9,
       -14,  -2,   6])

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [62]:
matr_rand = np.random.randint(-10,10, (5,5))

In [63]:
matr_rand

array([[-9, -7,  4,  1,  5],
       [-8, -9,  7,  5,  8],
       [-4,  6,  0, -5, -5],
       [ 0,  2,  6,  6,  9],
       [ 8, -1, -8,  8, -5]])

In [64]:
arr.shape

(16,)

In [65]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
matr_rand.size

25

In [68]:
matr_rand.shape

(5, 5)

In [77]:
matr_rand.max()

9

In [78]:
matr_rand.mean()

0.56

In [79]:
np.median(matr_rand)

1.0

In [80]:
np.mean(matr_rand)

0.56

In [81]:
matr_rand

array([[-9, -7,  4,  1,  5],
       [-8, -9,  7,  5,  8],
       [-4,  6,  0, -5, -5],
       [ 0,  2,  6,  6,  9],
       [ 8, -1, -8,  8, -5]])

In [82]:
matr_rand.argmax()

19

In [84]:
matr_rand.argmin()

0

In [86]:
matr_rand.min()

-9

In [96]:
matr_rand[3][4] # max value

9

In [100]:
matr_rand.shape

(5, 5)

In [103]:
matr_rand.reshape(25,)

array([-9, -7,  4,  1,  5, -8, -9,  7,  5,  8, -4,  6,  0, -5, -5,  0,  2,
        6,  6,  9,  8, -1, -8,  8, -5])

In [106]:
matr_rand.reshape(25,).max()

9

In [107]:
matr_rand.reshape(25,).argmax()

19