In [2]:
import numpy as np

In [4]:
arr = np.arange(0, 11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [9]:
arr[5:8]


array([5, 6, 7])

In [13]:
arr[:11:2]

array([ 0,  2,  4,  6,  8, 10])

In [15]:
arr[:11:2] *= 2

In [16]:
arr

array([ 0,  1,  8,  3, 16,  5, 24,  7, 32,  9, 40])

In [17]:
arr_test = arr.copy()

In [18]:
arr_test

array([ 0,  1,  8,  3, 16,  5, 24,  7, 32,  9, 40])

In [19]:
arr_test = np.arange(0,11)

In [23]:
arr_test.mean()

5.0

In [26]:
np.median(arr_test)

5.0

In [27]:
arr_test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
arr

array([ 0,  1,  8,  3, 16,  5, 24,  7, 32,  9, 40])

In [31]:
arr_2d = np.random.randint(0, 20, (2,2), dtype = int)

In [32]:
arr_2d

array([[ 0, 19],
       [ 9,  4]])

In [33]:
arr_2d_test = arr_2d.copy()

In [44]:
arr_2d_test = np.array([[1,2,3],
                         [10, 20, 30],
                         [25, 50, 75]])

In [45]:
arr_2d_test

array([[ 1,  2,  3],
       [10, 20, 30],
       [25, 50, 75]])

In [46]:
matr_2d = arr_2d_test

In [47]:
matr_2d

array([[ 1,  2,  3],
       [10, 20, 30],
       [25, 50, 75]])

In [49]:
matr_2d[0][2]

3

In [50]:
matr_2d[0,2]

3

In [54]:
matr_2d[:1,2:]

array([[3]])

In [55]:
matr_2d > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [56]:
tr_matr = matr_2d > 2

In [59]:
matr_2d[tr_matr]

array([ 3, 10, 20, 30, 25, 50, 75])

In [61]:
matr_2d[matr_2d > 2]

array([ 3, 10, 20, 30, 25, 50, 75])

In [63]:
matr_2d.shape

(3, 3)

In [72]:
arr_2d_test = matr_2d.reshape(9, )

In [74]:
arr_2d_test

array([ 1,  2,  3, 10, 20, 30, 25, 50, 75])

In [76]:
matr = np.arange(50).reshape(5, 10)

In [77]:
matr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [82]:
matr[1:4, 4:7]

array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])